# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entropiq < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.55"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.55/entropiq_1.22.55_darwin_amd64.zip"
    sha256 "290d003f8ca67bae4d9862e27d8c511bf17e351e399fa0d6acbdbd6f6d0648ae"

    def install
      bin.install "release/mac/amd64/binary/entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.55/entropiq_1.22.55_darwin_arm64.zip"
    sha256 "d4724833a87ce8678b47c6246a0687779eb6c1643ccf04438144c3cbb429b65b"

    def install
      bin.install "release/mac/arm64/binary/entropiq"
    end
  end
end
