# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12263 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.63"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.63/entropiq_1.22.63_darwin_amd64.tar.gz"
    sha256 "a279484c91e312f0134f10044ae28ad3fc16a8e57ee7f443797ea12fd875fe7f"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.63/entropiq_1.22.63_darwin_arm64.tar.gz"
    sha256 "b85cd0924c42f6ab0df97b3bec0142f9c8d37384bbac729a10498fe80b8f527e"

    def install
      bin.install "entropiq"
    end
  end
end
