# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12234 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.34"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.34/entropiq_1.22.34_darwin_amd64.tar.gz"
    sha256 "786d3f8caa519c6f78ae90ac6afef484a6dccdfef63cf28f1b46f63614f6d972"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.34/entropiq_1.22.34_darwin_arm64.tar.gz"
    sha256 "f66f532e8b22e33f5369d807d35e61510f85aa0d5d09858643d72bac67d536c7"

    def install
      bin.install "entropiq"
    end
  end
end
