# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12256 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.56"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.56/entropiq_1.22.56_darwin_amd64.zip"
    sha256 "fbdedba51490e41db1dba95187dc229cfbfa965dde7b078fc0898f380567dfd5"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.56/entropiq_1.22.56_darwin_arm64.zip"
    sha256 "f06d305159f741eec4eddbf690b24aba3ca5d7fc27308642418e745e65f8f93f"

    def install
      bin.install "entropiq"
    end
  end
end
