# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12264 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.64"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.64/entropiq_1.22.64_darwin_amd64.tar.gz"
    sha256 "33fc0a2c9d4693d7f8f9f51c457187807979cfce18085d555e1a9119e6c07029"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.64/entropiq_1.22.64_darwin_arm64.tar.gz"
    sha256 "4568e105a3458bd702533487fb936b5f3c5e7575789f21d5e043f75c685a69ce"

    def install
      bin.install "entropiq"
    end
  end
end
