# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entropiq < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.31"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.31/entropiq_1.22.31_darwin_amd64.tar.gz"
    sha256 "0c4426a3950ab04a76c891c80760bc320e0cd40084f9feeab21af56f86fb1f4d"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.31/entropiq_1.22.31_darwin_arm64.tar.gz"
    sha256 "9a4e1ab26256e402d634a68ed68dcf8af59ae6a4720016b9180adc28859ba978"

    def install
      bin.install "entropiq"
    end
  end
end
