# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT2 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "2.0.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/2.0.3/entropiq_2.0.3_darwin_amd64.tar.gz"
    sha256 "100dc9448ee975fd4b941ef4ccd1ea2a89fbf2c4db75581a047b328e96894b10"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/2.0.3/entropiq_2.0.3_darwin_arm64.tar.gz"
    sha256 "f0b21312a2b59280ea2253f1233c1ec95d44b6f6f5a64407081278a6cc50e936"

    def install
      bin.install "entropiq"
    end
  end
end
