# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT2 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "2.0.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/2.0.1/entropiq_2.0.1_darwin_amd64.tar.gz"
    sha256 "62c7f104bcbd607693eb8c192ed574619b950c7afa032598f9dac5c038b83879"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/2.0.1/entropiq_2.0.1_darwin_arm64.tar.gz"
    sha256 "cc3b3390b0735b3b3aa6f1e1d861d78bbea91a7d7727444194f2e5ef2055b102"

    def install
      bin.install "entropiq"
    end
  end
end
