# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12259 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.59"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.59/entropiq_1.22.59_darwin_amd64.tar.gz"
    sha256 "003c323454c1f1061e05c18ba594da3de034732616017708b90b6eb929e579a6"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.59/entropiq_1.22.59_darwin_arm64.tar.gz"
    sha256 "e13c4b0116c283791fe710adcaf09341546f63fcfc57c3bf0419a0ebb7b55469"

    def install
      bin.install "entropiq"
    end
  end
end
