# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT2 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "2.0.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/2.0.4/entropiq_2.0.4_darwin_amd64.tar.gz"
    sha256 "5afe26c9cec368e61054b5f840c410b2e7dea3e950bac5173e286ec41e334214"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/2.0.4/entropiq_2.0.4_darwin_arm64.tar.gz"
    sha256 "e7b84df6f8ddec2dfc0a4d48f861a5ad50f95728f0e208bc1964d08357a303f2"

    def install
      bin.install "entropiq"
    end
  end
end
