# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12268 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.68"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.68/entropiq_1.22.68_darwin_amd64.tar.gz"
    sha256 "bdd4262fc185e33388ef35d481228e9eb8342d6fc409a803fbd37d24016ae629"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.68/entropiq_1.22.68_darwin_arm64.tar.gz"
    sha256 "7e8b2842cb91bec8335be82e95d41baed2ca6afbaecaef8dab6651562474e97e"

    def install
      bin.install "entropiq"
    end
  end
end
