# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT1 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.35"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.35/entropiq_1.22.35_darwin_amd64.tar.gz"
    sha256 "2d904ed43e5d9c119c4951faa04697b0c11d0f1f0075a9b6c68631bf2ebcc753"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/entropiqinc/agent/releases/download/1.22.35/entropiq_1.22.35_darwin_arm64.tar.gz"
    sha256 "4894df356d5de2895add4fe20c2dcb462f26b3863faed86023dc4632d97e9ab6"

    def install
      bin.install "entropiq"
    end
  end
end
